### PR TITLE
Fixing 99% usb install on 5.x + ignore required FW version

### PR DESCRIPTION
**Pull request by tiliarou**
Would you consider merging this change by satteliteseeker ?
Does it reduce perf due to buffer size change ?

### CODE REVIEW

**Comment by XorTroll** [comment]
Have you tested USB installation after changing this? Does it work?

**Comment by tiliarou** [comment]
I didn't actually, don't have my switch under hand as of now but planning to test.
Reports are on the tinfoil gbatemp thread: https://gbatemp.net/threads/tinfoil-title-installer-manager-by-adubbz.511763/page-45#post-8340197
https://gbatemp.net/threads/tinfoil-title-installer-manager-by-adubbz.511763/page-45#post-8340259

https://gbatemp.net/goto/post?id=8338640#post-8338640

Not sure if they reported the fix for 5.x works or the min FW req check disabling works...
Might be good to hold on a bit before merging.

**Comment by XorTroll** [comment]
Yeah, try this and if it seems to work, then it'll be merged

**Comment by co5mo** [comment]
this one fixed it https://github.com/satelliteseeker/Tinfoil/releases/tag/v0.2.1-USB-fix

**Comment by XorTroll** [comment]
Well, merging it, nice work @satelliteseeker and the people who made this

**Comment by tiliarou** [comment]
@XorTroll actually there is a corruption issue :(
Fixed in latest commit from @satelliteseeker 
https://github.com/satelliteseeker/Tinfoil/commit/f33c735e3fda9e8127ec3b3b5f7296a438dc9a2c

**Comment by co5mo** [comment]
@tiliarou please make a new pr for the latest @satelliteseeker commit

**Pull request merged**
